version: '3.4'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  mp4giffrontend:
    image: mp4giffrontend
    build:
      context: mp4-gif-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:80

  mp4gifconverter:
    image: mp4gifconverter
    build:
      context: mp4gifconverter
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  kafka-network:
    driver: bridge
  app-network:
    driver: bridge